### ISSUE TITLE
/PRESENTATION/HTML/TOP/INDEX.HTML

### ISSUE THREAD

**Issue by skupu** [lymanepp/ha-epson-workforce#3]
Hi,

I have L355 and the status page has different url:

printerIP/PRESENTATION/HTML/TOP/INDEX.HTML

Is it possible to intergate?

**Comment by skupu** [comment]
Invalid config for 'epson_workforce' from integration 'sensor' at configuration.yaml, line 491: 'path' is an invalid option for 'sensor.epson_workforce', check: path

**Comment by lymanepp** [comment]
Fixed. Please try again.

**Comment by skupu** [comment]
Now it's OK. The sensors are visible, however the state is unknown. I think this is because the printer on the site only presents "L355 Series" on a blank page. Might be that the data is not there - I will try to investigate.
