### ISSUE TITLE
Other Epson Printers

### ISSUE THREAD

**Issue by Doka85** [lymanepp/ha-epson-workforce#5]
Hi,

I have an Epson XP-860 for which your integration did not fit. So I adapted the code so that it works for me, even though I don't actually have any programming skills. (Between zero and a little bit)

The only question is whether you might want to include the code with you, or perhaps even combine it into an integration? Or if you don't want to do all that, can I publish the code with a reference to yourself?

Greets
Manuel

[epson_XP.zip](https://github.com/user-attachments/files/18135809/epson_XP.zip)

**Comment by lymanepp** [comment]
I added support for lightmagenta and lightcyan. Please try it.

**Comment by Doka85** [comment]
yes, it looks like it will work! =)
