### ISSUE TITLE
Printer state sensor

### ISSUE THREAD

**Issue by KameDomotics** [lymanepp/ha-epson-workforce#6]
Is it possible to implement a sensor that indicates the printer on/off status?

Thanks.

**Comment by lymanepp** [comment]
Is the http://<IP-ADDR>/PRESENTATION/HTML/TOP/PRTINFO.HTML page viewable when the printer is off? Is the IP-ADDR pingable with the printer off?

**Comment by KameDomotics** [comment]
> Is the http://IP-ADDR/PRESENTATION/HTML/TOP/PRTINFO.HTML page viewable when the printer is off? Is the IP-ADDR pingable with the printer off?

No, unfortunately when the printer is off (Epson XP-2150) it is not pingable. 
Would it be possible to create a sensor that pings the printer, if it is reachable it returns ON status, if it is not reachable it returns OFF status?

**Comment by lymanepp** [comment]
Use the https://www.home-assistant.io/integrations/ping/ integration to ping the printer.
